//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Regulations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Regulations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APS.Resources.Regulations", typeof(Regulations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - General rules
        ///The use of the site defines all the terms of the consent, which will be discussed below. In case the user disagrees with the terms, he must refuse to use the site further.
        ///- General terms of use
        ///The User assumes full responsibility for the content of the advertisement, in accordance with the program rules and national laws.
        ///Creating and publishing ads is only allowed for registered users.
        ///The user is able to publish, remove from the publication, re-publish their advertisements.
        ///- Prohi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Classified_Rules_Description {
            get {
                return ResourceManager.GetString("Classified_Rules_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of ad placement.
        /// </summary>
        public static string Classified_Rules_Title {
            get {
                return ResourceManager.GetString("Classified_Rules_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - General conditions
        ///The agreement applies to all information provided by the user during the use of the site. The use of the site means the consent of the user based on the conditions for processing his personal information. In case the user does not agree with the given conditions, he must refrain from using the further site.
        ///- User profile
        ///The information provided by the user must be true and up-to-date. If there is any doubt as to the veracity of the information provided, the user profile will be blo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Classified_User_Description {
            get {
                return ResourceManager.GetString("Classified_User_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Confidentiality Agreement.
        /// </summary>
        public static string Classified_User_Title {
            get {
                return ResourceManager.GetString("Classified_User_Title", resourceCulture);
            }
        }
    }
}
